- id: '1673566395889'
  alias: Backup Home Assistant every night at 12 AM
  description: ''
  trigger:
    - platform: time
      at: '12:00:00'
  condition: [ ]
  action:
    - service: hassio.backup_full
      data:
        compressed: true
  mode: single
- id: '1675296737776'
  alias: LG webOS Smart TV - Turn On Action
  description: Get Living Room Ready for Watch Movies
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: MovieTime
  condition: [ ]
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_webos_smart_tv
      webostv_mac: 64:cb:e9:ad:49:8a
      on_action:
        - type: turn_on
          device_id: 71f5e63d2e1300c044ae37d0e248ece3
          entity_id: light.rgbic_tv_backlight
          domain: light
        - service: media_player.turn_on
          data: { }
          target:
            device_id: dec685bea5d01d67d0d431f8b35cfa43
        - service: webostv.select_sound_output
          data:
            entity_id: media_player.lg_webos_smart_tv
            sound_output: external_arc
        - service: media_player.select_source
          data:
            source: Apple OTT
          target:
            device_id: 41d41c8d5c3675a9851458d0127fb9b5
- id: '1675354408045'
  alias: Turn Off Kid Bedroom Devices
  description: ''
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: KidBedTime
  condition: [ ]
  action:
    - service: light.turn_off
      data: { }
      target:
        entity_id: light.kid_bedroom_light
    - service: fan.turn_off
      data: { }
      target:
        entity_id: fan.kid_bedroom_fan
    - service: switch.turn_off
      target:
        entity_id: switch.maxi_tv_plug
      data: { }
  mode: single
- id: '1675354961466'
  alias: Bed Time
  description: ''
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: HomeBedTime
  condition: [ ]
  action:
    - service: fan.turn_off
      data: { }
      target:
        entity_id:
          - fan.office_fan
          - fan.living_room_fan
    - service: light.turn_off
      data: { }
      target:
        entity_id: light.homelightsexceptkid
    - service: switch.turn_off
      data: { }
      target:
        entity_id: switch.homeswitchesexceptoutside
    - service: fan.turn_on
      data:
        percentage: 100
      target:
        entity_id:
          - fan.kid_bedroom_fan
          - fan.master_bedroom_fan
    - service: climate.turn_on
      target:
        entity_id: climate.home
      data: { }
    - service: climate.set_hvac_mode
      data:
        hvac_mode: cool
      target:
        entity_id: climate.home
    - service: climate.set_fan_mode
      data:
        fan_mode: auto
      target:
        entity_id: climate.home
    - service: climate.set_temperature
      data:
        hvac_mode: cool
        temperature: 70
      target:
        entity_id: climate.home
  mode: single
- id: '1675703001663'
  alias: Turn off HVAC
  description: ''
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: HvacOff
    - platform: time
      at: 07:30:00
  condition:
    - condition: template
      value_template: '{{ state_attr(''climate.home'', ''state'') == ''on'' }}'
  action:
    - service: climate.set_fan_mode
      data:
        fan_mode: 'off'
      target:
        entity_id: climate.home
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'off'
      target:
        entity_id: climate.home
  mode: single
- id: '1675884634266'
  alias: Turn HVAC On
  description: ''
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: HvacOn
    - platform: time
      at: '22:30:00'
  condition:
    - condition: template
      value_template: '{{ state_attr(''climate.home'', ''state'') == ''off'' or state_attr(''weather.home'',
      ''temperature'') >=76 }}'
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.home
    - service: climate.set_hvac_mode
      data:
        hvac_mode: cool
      target:
        entity_id: climate.home
    - service: climate.set_fan_mode
      data:
        fan_mode: auto
      target:
        entity_id: climate.home
    - service: climate.set_temperature
      data:
        temperature: 72
      target:
        entity_id: climate.home
  mode: single
- id: '1676330625685'
  alias: Set Bedroom Movie Time
  description: ''
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: BedroomMovieTime
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_webos_smart_tv_2
      webostv_mac: ac:5a:f0:3c:e3:e8
      on_action:
        - service: webostv.select_sound_output
          data:
            entity_id: media_player.lg_webos_smart_tv_2
            sound_output: external_optical
        - service: media_player.select_source
          data:
            source: Apple OTT
          target:
            entity_id: media_player.lg_webos_smart_tv_2
        - service: fan.turn_on
          data:
            percentage: 100
          target:
            entity_id: fan.master_bedroom_fan
        - service: light.turn_off
          data: { }
          target:
            entity_id: light.master_bedroom_light
- id: '1676394605387'
  alias: Setup Office for Work
  description: ''
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: WorkTime
  condition: [ ]
  action:
    - if:
        - condition: state
          entity_id: fan.office_fan
          state: "off"
        - condition: state
          entity_id: climate.home
          state: 'off'
        - condition: numeric_state
          entity_id: weather.home
          attribute: temperature
          above: 75
      then:
        - service: fan.turn_on
          data:
            percentage: 100
          target:
            entity_id: fan.office_fan
    - if:
        - condition: state
          entity_id: light.office_light
          state: 'off'
      then:
        - service: light.turn_on
          target:
            entity_id: light.office_light
  mode: single
- id: '1676394856684'
  alias: Work  Done
  description: ''
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: WorkDone
  condition: []
  action:
    - if:
        - condition: state
          entity_id: fan.office_fan
          state: "on"
      then:
        - service: fan.turn_off
          data: {}
          target:
            entity_id: fan.office_fan
    - if:
        - condition: state
          entity_id: light.office_light
          state: 'on'
      then:
        - service: light.turn_off
          target:
            entity_id: light.office_light
  mode: single
