- id: '1673566395889'
  alias: Backup Home Assistant every night at 12 AM
  description: ''
  trigger:
  - platform: time
    at: '12:00:00'
  condition: []
  action:
  - service: hassio.backup_full
    data:
      compressed: true
  mode: single
- id: '1675296737776'
  alias: LG webOS Smart TV - Turn On Action
  description: Get Living Room Ready for Watch Movies
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: MovieTime
  condition: []
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_webos_smart_tv
      webostv_mac: 64:cb:e9:ad:49:8a
      on_action:
      - type: turn_on
        device_id: 71f5e63d2e1300c044ae37d0e248ece3
        entity_id: light.rgbic_tv_backlight
        domain: light
      - service: media_player.turn_on
        data: {}
        target:
          device_id: dec685bea5d01d67d0d431f8b35cfa43
      - service: webostv.select_sound_output
        data:
          entity_id: media_player.lg_webos_smart_tv
          sound_output: external_arc
      - service: media_player.select_source
        data:
          source: Apple OTT
        target:
          device_id: 41d41c8d5c3675a9851458d0127fb9b5
- id: '1675354408045'
  alias: Turn Off Kid Bedroom Devices
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: KidBedTime
  condition: []
  action:
  - if: '{{ is_state(''fan.kid_bedroom'', ''on'') }}'
    then:
    - service: fan.turn_off
      data: {}
      target:
        entity_id: fan.kid_bedroom
  - if: '{{ is_state(''light.kid_bedroom'', ''on'') }}'
    then:
    - service: light.turn_off
      target:
        entity_id: light.kid_bedroom
  - if: '{{ is_state(''media_player.tv_kid_bedroom'', ''on'') }}'
    then:
    - service: media_player.turn_off
      target:
        entity_id: media_player.tv_kid_bedroom
  - if: '{{ is_state(''remote.atv_kid_bedroom'', ''on'') }}'
    then:
    - service: remote.turn_off
      target:
        entity_id: remote.atv_kid_bedroom
  mode: single
- id: '1675354961466'
  alias: Bed Time
  description: Prepare the home for bed time
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: HomeBedTime
  condition: []
  action:
  - service: fan.turn_off
    data: {}
    target:
      entity_id: fan.to_be_turn_off_on_bedtime
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.to_be_turn_off_on_bedtime
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.to_be_turn_off_on_bedtime
  - if:
    - '{{ is_state(''climate.home'', ''off'') }}'
    - '{{ state_attr(''weather.home'', ''temperature'') >= 72 }}'
    then:
    - service: climate.turn_on
      data: {}
      target:
        entity_id: climate.home
    - service: climate.set_hvac_mode
      data:
        hvac_mode: cool
      target:
        entity_id: climate.home
    - service: climate.set_fan_mode
      data:
        fan_mode: auto
      target:
        entity_id: climate.home
    - service: climate.set_temperature
      data:
        temperature: 70
      target:
        entity_id: climate.home
  - if:
    - '{{ is_state(''fan.kid_bedroom'', ''off'') }}'
    - '{{ is_state(''fan.master_bedroom'', ''off'') }}'
    then:
    - service: fan.turn_on
      data:
        percentage: 100
      target:
        entity_id: fan.bedroom_fans
  mode: single
- id: '1675703001663'
  alias: Turn OFF the AC
  description: Turn OFF the AC by event or at 07:30 AN
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: HvacOff
  - platform: time
    at: 07:30:00
  condition: []
  action:
  - if: '{{ is_state(''climate.home'', ''on'') }}'
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: false
      target:
        entity_id: climate.home
    - service: climate.set_fan_mode
      data:
        fan_mode: false
      target:
        entity_id: climate.home
    - service: climate.turn_off
      data: {}
      target:
        entity_id: climate.home
  mode: single
- id: '1675884634266'
  alias: Turn ON the AC
  description: Turn on the AC at 70 °F by firing an event or at 10:30 PM
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: HvacOn
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - if:
    - '{{ is_state(''climate.home'', ''off'') }}'
    - '{{ state_attr(''weather.home'', ''temperature'') >= 72 }}'
    then:
    - service: climate.turn_on
      data: {}
      target:
        entity_id: climate.home
    - service: climate.set_hvac_mode
      data:
        hvac_mode: cool
      target:
        entity_id: climate.home
    - service: climate.set_fan_mode
      data:
        fan_mode: auto
      target:
        entity_id: climate.home
    - service: climate.set_temperature
      data:
        temperature: 70
      target:
        entity_id: climate.home
  mode: single
- id: '1676330625685'
  alias: Set Bedroom Movie Time
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: BedroomMovieTime
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_webos_smart_tv_2
      webostv_mac: ac:5a:f0:3c:e3:e8
      on_action:
      - service: webostv.select_sound_output
        data:
          entity_id: media_player.lg_webos_smart_tv_2
          sound_output: external_optical
      - service: media_player.select_source
        data:
          source: Apple OTT
        target:
          entity_id: media_player.lg_webos_smart_tv_2
      - service: fan.turn_on
        data:
          percentage: 100
        target:
          entity_id: fan.master_bedroom_fan
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.master_bedroom_light
- id: '1676394605387'
  alias: Start Work Day
  description: Get the office ready for work
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: StartWorkDay
  condition: []
  action:
  - if:
    - '{{ is_state(''fan.office'', ''off'') }}'
    - '{{ is_state(''climate.home'', ''off'') }}'
    - '{{ state_attr(''weather.home'', ''temperature'') >= 74 }}'
    then:
    - service: fan.turn_on
      data:
        percentage: 100
      target:
        entity_id: fan.office
  - if:
    - condition: template
      value_template: '{{ is_state(''light.office'', ''off'') }}'
    then:
    - service: light.turn_on
      target:
        entity_id: light.office
      data: {}
  mode: single
- id: '1676394856684'
  alias: End Work Day
  description: Turn off the office devices
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: EndWorkDay
  condition: []
  action:
  - if: '{{ is_state(''fan.office'', ''on'') }}'
    then:
    - service: fan.turn_off
      data: {}
      target:
        entity_id: fan.office
  - if: '{{ is_state(''light.office'', ''on'') }}'
    then:
    - service: light.turn_off
      target:
        entity_id: light.office
  mode: single
