###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
###############################################################################

# Core Configuration. Do not remove.
homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 0
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  currency: USD
  internal_url: http://homeassistant.local:8123
  external_url: !secret external_url

default_config:

fontawesome:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace:
  mode: yaml
  dashboards:
    home-dashboard:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: ui-lovelace.yaml

  resources:
    - url: /hacsfiles/bootstrap-grid-card/bootstrap-grid-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity-row/battery-entity-row.js?v=1.3.1
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?v=0.4.4
      type: js
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.11.0
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module

wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

# Managed via UI
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
ios: !include ios.yaml

# Others
sensor: !include sensors.yaml

# Logger
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
    custom_components.localtuya.pytuya: debug