###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
###############################################################################

# Core Configuration. Do not remove.
homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 0
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  currency: USD
  internal_url: http://homeassistant.local:8123
  external_url: !secret external_url

default_config:
frontend:
  themes: !include_dir_merge_named themes
#  extra_module_url:
#    - /local/card-mod.js

#lovelace:
#  mode: yaml
#  resources:
#    - url: /local/bootstrap-grid-card.js
#      type: module
#    - url: /local/stack-in-card.js
#      type: module
#    - url: /local/battery-entity-row.js?v=1.3.1
#      type: module
#    - url: /hacsfiles/weather-card/weather-card.js
#      type: module
#    - url: /hacsfiles/battery-state-card/battery-state-card.js
#      type: module
#    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
#      type: module
#    - url: /local/vertical-stack-in-card.js?v=0.4.4
#      type: js
#    - url: /local/community/home-assistant-sun-card.js
#      type: js
#    - url: /local/mini-graph-card-bundle.js?v=0.11.0
#      type: module
#    - url: /local/mushroom.js
#      type: module

wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

# Managed via UI
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
ios: !include ios.yaml

# Others
sensor: !include sensors.yaml

# Logger
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
    custom_components.localtuya.pytuya: debug