# QNAP
- platform: qnap
  host: !secret qnap_host
  username: !secret qnap_username
  password: !secret qnap_password
  monitored_conditions:
    - status
    - system_temp
    - cpu_temp
    - cpu_usage
    - memory_used
    - memory_percent_used
    - network_link_status
    - network_tx
    - network_rx
    - drive_smart_status
    - drive_temp
    - volume_percentage_used

- platform: template
  sensors:
    # convert value from add-in into statistic
    water_meter_total_gal:
      friendly_name: "Total Water Consumption"
      device_class: water
      unit_of_measurement: gal
      value_template: "{{ ((states('sensor.water_meter_consumption') | float))  }}"
      attribute_templates:
        state_class: total_increasing